<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace>EGPU.TrayToggle</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <None Update="status-on.ico" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <None Update="status-off.ico" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
  <Target Name="CopyStatusIconsToPublishDirectory" AfterTargets="Publish">
    <Copy SourceFiles="$(MSBuildProjectDirectory)\status-on.ico;$(MSBuildProjectDirectory)\status-off.ico" DestinationFolder="$(PublishDir)" />
  </Target>
</Project>
